/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chris_video_RTMPPublisher */

#ifndef _Included_com_chris_video_RTMPPublisher
#define _Included_com_chris_video_RTMPPublisher
#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT void JNICALL Java_com_chris_video_RTMPPublisher_setAudioPipeId
  (JNIEnv * env, jobject obj, jint audioPipeId);

JNIEXPORT void JNICALL Java_com_chris_video_RTMPPublisher_setVideoPipeId
  (JNIEnv * env, jobject obj, jint videoPipeId);


/*
 * Class:     com_chris_video_RTMPPublisher
 * Method:    publish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_chris_video_RTMPPublisher_publish
  (JNIEnv * env, jobject obj);



#ifdef __cplusplus
}
#endif
#endif
