#ifndef LIVE_STATE_H_
#define LIVE_STATE_H_

enum SENDER_EVENT{
	ID_SENDER_EVENT_CREATE,
	ID_SENDER_EVENT_SHUTDOWN,
	ID_SENDER_EVENT_CONNECT,
	ID_SENDER_EVENT_CLOSE,
	ID_SENDER_EVENT_START,
	ID_SENDER_EVENT_STOP,
	ID_SENDER_EVENT_PAUSE,
	ID_SENDER_EVENT_RESUME,
	ID_SENDER_EVENT_SET_CALLBACK,
	ID_SENDER_EVENT_SEND_CMD,
	ID_SENDER_EVENT_TAIL

};

enum SENDER_INTERNAL_STATE{
	ID_SENDER_STATE_IDLE = 100,
	ID_SENDER_STATE_INITED = 101,
	ID_SENDER_STATE_CONNECT_ESTABLISHED = 102,
	ID_SENDER_STATE_PUBLISHING = 103,
	ID_SENDER_STATE_PUBLISH_WAITING = 104,
	ID_SENDER_STATE_CONNECT_CLOSED = 105
};


enum SENDER_INTERAL_ERROR{

	ID_SENDER_ERROR_CONNECT_FAIL_PREPARE = -1,
	ID_SENDER_ERROR_CONNECT_FAIL_PUB = -2,
	ID_SENDER_ERROR_AUDIO_ENGINE_FAIL_CREATE = -3,
	ID_SENDER_ERROR_AUDIO_ENGINE_FAIL_RELEASE = -4,
	ID_SENDER_ERROR_AUDIO_RECORDER_FAIL_CREATE = -5,
	ID_SENDER_ERROR_AUDIO_RECORDER_FAIL_START = -6,

	ID_SENDER_ERROR_INVALID_OP = -100
};


#endif /* LIVE_STATE_H_ */
